FROM node:16-alpine
ENV CI=true
ENV WDS_SOCKET_PORT=0
 
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]

# Before Using Skaffold!!
# FROM node:16-alpine
# USER node
# RUN mkdir -p /home/node/app
# WORKDIR '/home/node/app'
# COPY --chown=node:node ./package.json ./
# RUN npm install
# COPY --chown=node:node ./ ./
# CMD [ "npm", "start" ]